#!/usr/bin/perl
# ---------------------------------------------------------------------------
# $Id$
#
# wrapper for calling ARC programs that are installed in /usr/local/bin
# 
# ---------------------------------------------------------------------------

use strict;
use warnings;
use File::Basename;

# globals, set during installation
my $arc_basedir = 'CHANGEME_ARC_BASEDIR';
my $kim_basedir = 'CHANGEME_KIM_BASEDIR';
my $tim_basedir = 'CHANGEME_TIM_BASEDIR';

sub get_path($);
sub main();


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------
sub main() {

   my $cmdname = basename($0);
   my $cmd = get_path($cmdname);

   # set environment
   $ENV{ARC_BASEDIR} = $arc_basedir;
   $ENV{KIM_BASEDIR} = $kim_basedir;
   $ENV{TIM_BASEDIR} = $tim_basedir;
   $ENV{PERL5LIB} = $arc_basedir . '/perllib';

   die('arc_wrapper: invalid command') unless $cmd;
   unshift(@ARGV, $cmd);
   #print "calling: ", join(' ', @ARGV) . "\n";
   exec @ARGV;
}

# ---------------------------------------------------------------------------
# get path to the given progam - must be an ARC program we know about
# ---------------------------------------------------------------------------
sub get_path($) {
   my $prog = shift;

   # ARC generic utilities
   if    ( $prog =~ m/sqlt/ 
        || $prog =~ m/pgloadcsv/ 
        || $prog =~ m/pgdumpcsv/ 
   ) {
      return $arc_basedir . "/util/$prog";
   }
   # KIM executables
   elsif ( $prog =~ m/kim/ 
        || $prog =~ m/satpos/ 
        || $prog =~ m/unload_resolve/ 
        || $prog =~ m/stage_source/ 
   ) {
      return $kim_basedir . "/bin/$prog";
   }
   # TIM executables
   elsif ( $prog =~ m/tim/ 
        #|| $prog =~ m/piis/ 
        #|| $prog =~ m/timidcrypt/ 
        #|| $prog =~ m/addtimid/ 
        #|| $prog =~ m/csvfix/ 
   ) {
      return $tim_basedir . "/bin/$prog";
   }

   return '';
}

main();
1;




